#!/usr/bin/env bash
# This script audits subdomains for A records and displays their IP destinations

get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    dig "${subdomain}.${domain}" +short | awk -v sub="$subdomain" 'NR==1 { print "The subdomain " sub " is a A record and points to " $1 }'
}

if [ $# -eq 1 ]; then
    domain=$1
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
elif [ $# -eq 2 ]; then
    domain=$1
    subdomain=$2
    get_subdomain_info "$domain" "$subdomain"
else
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
