#!/usr/bin/env bash
# This script creates an RSA key pair with 4096 bits, named 'school', and passphrase 'betty'

rm -f school school.pub 2>/dev/null
ssh-keygen -t rsa -b 4096 -f school -N "betty" <<< y
